import { event } from "../../../types/CDM";

export const data: event = {
    id: 0,
    sat1_object_designator: "",
    sat2_object_designator: "",
    cdms: [
    {
        id: 0,
        created_at: (Date.now() - 24 * 60 * 60 * 1000).toString(),
        collision_probability: Math.random() * 0.1,
        miss_distance: Math.random() * 1000,
        sat1_cn_n: Math.random() * 0.1,
        sat1_cr_r: Math.random() * 0.1,
        sat1_ct_t: Math.random() * 0.1,
        sat2_cn_n: Math.random() * 0.1,
        sat2_cr_r: Math.random() * 0.1,
        sat2_ct_t: Math.random() * 0.1,
    },
    {
        id: 1,
        created_at: (Date.now() - 20 * 60 * 60 * 1000).toString(),
        collision_probability: Math.random() * 0.1 + 0.05,
        miss_distance: Math.random() * 900,
        sat1_cn_n: Math.random() * 0.1,
        sat1_cr_r: Math.random() * 0.1,
        sat1_ct_t: Math.random() * 0.1,
        sat2_cn_n: Math.random() * 0.1,
        sat2_cr_r: Math.random() * 0.1,
        sat2_ct_t: Math.random() * 0.1,
    },
    {
        id: 2,
        created_at: (Date.now() - 16 * 60 * 60 * 1000).toString(),
        collision_probability: Math.random() * 0.1 + 0.15,
        miss_distance: Math.random() * 800,
        sat1_cn_n: Math.random() * 0.1,
        sat1_cr_r: Math.random() * 0.1,
        sat1_ct_t: Math.random() * 0.1,
        sat2_cn_n: Math.random() * 0.1,
        sat2_cr_r: Math.random() * 0.1,
        sat2_ct_t: Math.random() * 0.1,
    },
    {
        id: 3,
        created_at: (Date.now() - 12 * 60 * 60 * 1000).toString(),
        collision_probability: Math.random() * 0.1 + 0.25,
        miss_distance: Math.random() * 700,
        sat1_cn_n: Math.random() * 0.1,
        sat1_cr_r: Math.random() * 0.1,
        sat1_ct_t: Math.random() * 0.1,
        sat2_cn_n: Math.random() * 0.1,
        sat2_cr_r: Math.random() * 0.1,
        sat2_ct_t: Math.random() * 0.1,
    },
    {
        id: 4,
        created_at: (Date.now() - 8 * 60 * 60 * 1000).toString(),
        collision_probability: Math.random() * 0.1 + 0.35,
        miss_distance: Math.random() * 600,
        sat1_cn_n: Math.random() * 0.1,
        sat1_cr_r: Math.random() * 0.1,
        sat1_ct_t: Math.random() * 0.1,
        sat2_cn_n: Math.random() * 0.1,
        sat2_cr_r: Math.random() * 0.1,
        sat2_ct_t: Math.random() * 0.1,
    },
    {
        id: 5,
        created_at: (Date.now() - 4 * 60 * 60 * 1000).toString(),
        collision_probability: Math.random() * 0.1 + 0.45,
        miss_distance: Math.random() * 500,
        sat1_cn_n: Math.random() * 0.1,
        sat1_cr_r: Math.random() * 0.1,
        sat1_ct_t: Math.random() * 0.1,
        sat2_cn_n: Math.random() * 0.1,
        sat2_cr_r: Math.random() * 0.1,
        sat2_ct_t: Math.random() * 0.1,
    },
    {
        id: 6,
        created_at: Date.now().toString(),
        collision_probability: Math.random() * 0.1 + 0.55,
        miss_distance: Math.random() * 400,
        sat1_cn_n: Math.random() * 0.1,
        sat1_cr_r: Math.random() * 0.1,
        sat1_ct_t: Math.random() * 0.1,
        sat2_cn_n: Math.random() * 0.1,
        sat2_cr_r: Math.random() * 0.1,
        sat2_ct_t: Math.random() * 0.1,
    }],
};